<a href="https://colab.research.google.com/github/19pa1a0204/AI-Lab/blob/master/Experiment%20_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment No1 : Numpy
 
 
##1) Different ways to create a NumPy arrays.

In [ ]:
import numpy as np
a = np.array([1,2,3])
print (a)

[1 2 3]


In [ ]:
p = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


##2)Add,remove,modify elements in an array.

###a.Add

In [ ]:
b = np.append(a,[4,5,6])
print(b)

[1 2 3 4 5 6]


###b.Remove

In [ ]:
c = np.delete(a,[1,2])
print(c)

[1]


###c.Modify

In [ ]:
d = np.array([1,2,3,4,5,6])
d[d<2]=-1
print(d)

[-1  2  3  4  5  6]


##3) Arithmetic operations on NumPy array.

In [ ]:
import numpy as np
a = np.random.random((2,3))
b = np.random.random((2,3))
sum=np.add(a,b)
diff=np.subtract(a,b)
prod=np.multiply(a,b)
quo=np.divide(a,b)
mod=np.mod(a,b)
pow=np.power(a,b)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.32554555 1.67157971 1.27870477]
 [0.45456299 1.51911372 0.32201559]]
[[ 0.48241317  0.18967471  0.12873398]
 [-0.37685459 -0.10625275 -0.11401333]]
[[0.38108714 0.68955055 0.40462837]
 [0.01615203 0.57410421 0.02267375]]
[[2.14433553 1.25598768 1.22389086]
 [0.09346495 0.86925687 0.47703775]]
[[0.06084698 0.18967471 0.12873398]
 [0.0388542  0.70643049 0.10400113]]
[[0.95833624 0.94812219 0.81706564]
 [0.25918924 0.75394777 0.61052026]]


##4) Slicing and iterating of NumPy arrays.

###a.Slicing

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print (arr[2:4])

[3 4]


###b.Iterating

In [ ]:
for i in arr:
  print(i)

1
2
3
4
5
6


##5) Matrix operation on NumPy arrays.

In [ ]:
import numpy as np
a = np.array([[3,4],[3,4]])
b = np.array([[3,4],[3,4]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[[6 8]
 [6 8]]
[[0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]]
